server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: "sre-challenge-kafka-headless.kafka:9092"
    consumer:
      group-id: "back-group-local"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: "*"

  datasource.url: jdbc:postgresql://sre-challenge-pg-headless:5432/sre_challenge
  datasource.username: db_user
  datasource.password: password123
  datasource.driverClassName: org.postgresql.Driver

  jpa.hibernate.ddl-auto: update

# Actuator settings ##################################################
management:
  info.git.mode: full
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
      