server:
  port: 8080
spring:
  datasource.url: jdbc:postgresql://sre-challenge-pg.postgres.svc.cluster.local:5432/sre_challenge
  datasource.username: db_user
  datasource.password: password123
  datasource.driverClassName: org.postgresql.Driver

  jpa.hibernate.ddl-auto: validate

# Actuator settings ##################################################
management:
  info.git.mode: full
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
