name: Docker Image CI

on:
  push:
    branches: [ start ]
  pull_request:
    branches: [ start ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: gradle:jdk11-slim
    steps:
    - uses: actions/checkout@v2

    - name: Gradle Build
      run: ./gradlew clean build --info
    
    - name: list dir 
      run: ls -laR
