name: Docker Image CI

on:
  push:
    branches: [ gha ]
  pull_request:
    branches: [ gha ]

env:
  APP_VERSION: 0.1.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Gradle build all apps
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: List Dir
      run: ls -laR

    - name: Upload Artifact - JAR for app Back
      env:
        APP_NAME: back
      uses: actions/upload-artifact@v2
      with:
        name: sre-challenge-apps
        path: app/$APP_NAME/build/libs/$APP_NAME-$APP_VERSION.jar
        retention-days: 10
        if-no-files-found: error

    - name: Upload Artifact - JAR for app Front
      env:
        APP_NAME: front
      uses: actions/upload-artifact@v2
      with:
        name: sre-challenge-apps
        path: app/$APP_NAME/build/libs/$APP_NAME-$APP_VERSION.jar
        retention-days: 10
        if-no-files-found: error

    - name: Upload Artifact - JAR for app Reader
      env:
        APP_NAME: reader
      uses: actions/upload-artifact@v2
      with:
        name: sre-challenge-apps
        path: app/$APP_NAME/build/libs/$APP_NAME-$APP_VERSION.jar
        retention-days: 10
        if-no-files-found: error
